lab50:
  windows:
    -readme
    -editor
    -terminal
  files:
    - !exclude "*"
    - !include clean.py
    - !include silent_sea.txt
    - !include silent_sea_clean.txt
    - !exclude sol.txt
submit50:
  files:
    - !exclude "*"
    - !include "clean.py"
check50:
  files:
    - !exclude "*"
    - !require clean.py
    - !require sol.txt
    - !require silent_sea_clean.txt