check50:
  files:
    - !exclude *
    - include "binary.c"
  checks:
    make binary:
      - run: make binary
        exit: 0
    binary 10:
      - run: ./binary 10
        stdout: Number 10 is at index 0
        exit: 0
