lab50:
  windows:
    -readme
    -editor
    -terminal
  files:
    - !exclude "*"
    - !include tries.c
    - !include cities.txt
submit50:
  files:
    - !exclude "*"
    - !include "tries.c"
check50:
  files:
    - !exclude "*"
    - !require tries.c
    - !require cities.txt