lab50:
  files:
    - !exclude "*"
    - !include wizardry.c
    - !include hopwarts.txt
    - !include myletter.txt
    - !include README.md
check50:
  files:
    - !exclude "*"
    - !require wizardry.c