lab50:
  windows:
    -readme
    -editor
    -terminal
  files:
    - !exclude "*"
    - !include wizardry.c
    - !include hopwarts.txt
    - !include myletter.txt
check50:
  files:
    - !exclude "*"
    - !require wizardry.c
