lab50:
  windows:
    -readme
    -editor
    -terminal
  files:
    - !exclude "*"
    - !include time.py
submit50:
  files:
    - !exclude "*"
    - !include "time.py"
check50:
  files:
    - !exclude "*"
    - !require time.py
  dependencies:
    - pytz